FROM centos/mongodb-36-centos7:latest

USER root

ENV http_proxy=http://10.15.2.10:8080
ENV https_proxy=http://10.15.2.10:8080

RUN yum -y install epel-release ; \
    yum clean all ; \
    rm -rf /var/cache/yum

RUN yum -y update ; \
    yum clean all ; \
    rm -rf /var/cache/yum

RUN yum -y install java nginx ; \
    yum clean all ; \
    rm -rf /var/cache/yum

ENV http_proxy=
ENV https_proxy=
