---
apiVersion: v1
kind: Template
metadata:
  name: build-config-template
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: flareclient-ui
      name: flareclient-ui
    spec:
      output:
        pushSecret:
          name: ${DOCKER_PUSH_SECRET}
        to:
          kind: DockerImage
          name: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/flareclient-ui:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        type: Binary
      strategy:
        dockerStrategy:
          dockerfilePath: ./Dockerfile
          pullSecret:
            name: 'artifactory-puller'
        type: Docker
      triggers: []
parameters:
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: DOCKER_PUSH_SECRET
    displayName: Docker Push Secret
    description: Secret that will be used to push the docker image
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
