---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        external: flareclient-ui
      name: flareclient-ui
    spec:
      ports:
        - nodePort: 0
          port: 443
          protocol: TCP
          targetPort: 443
      sessionAffinity: None
      selector:
        name: flareclient-ui
      type: ClusterIP
    status:
      loadBalancer: {}